services:
  web:
    container_name: yueswater-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8088/api
      - SERVER_API_URL=http://yueswater-server:8088/api
    networks:
      - yueswater-network

networks:
  yueswater-network:
    external: true